config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations',
                                      omniauth_callbacks: 'callbacks',
                                      passwords: 'passwords',}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :search_product
      get :search_product_by_component
    end
    member do
      post :add_to_cart
      post :increase_quantity
      post :decrease_quantity
    end
    resources :cart_items do
      member do
        post :increase_quantity
        post :decrease_quantity
      end
    end
  end

  resources :carts do
    member do
      post :increase_quantity
      post :decrease_quantity
    end
  end

  resources :orders do
    resources :product_ratings_and_reviews
    collection do
      get :checkout
      post :submit_stripe_payment
    end

    member do
      get :stripe_payment
    end
  end


  resources :admin_dashboards do
    collection do
      get :pending_orders
      get :all_products
    end
    member do
      patch :change_customer_order_status
      get :download_order
    end
  end

  resources :add_to_wish_lists

end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController
  before_action :authenticate_admin

  def index
    @total_sales_over_time = Order.where(status: 'delivered').group_by_day(:updated_at).sum('total_price')
    @top_selling_products = OrderItem.joins(:product, :order)
                                     .where(orders: { status: 'delivered' })
                                     .group('products.name')
                                     .sum('quantity')
    @sales_by_payment_method = Order.where(status: 'delivered').group(:payment_method).sum('total_price')
    @total_users = User.count
    @confirmed_users = User.where.not(confirmed_at: nil).count
    @unconfirmed_users = User.where(confirmed_at: nil).count
    @admin_users = User.where(is_admin: true).count
    @products_by_component = Product.group(:component).sum(:quantity)
  end

  def show
    @pending_order = Order.includes(:user, order_items: :product).find(params[:id])
  end


  def pending_orders
    @pending_orders = Order.includes(:user, order_items: :product)
                           .where(status: ['processing', 'shipped', 'delivered'])
                           .page(params[:page]).per(10)
  end

  def change_customer_order_status
    @pending_order = Order.find(params[:id])
    old_status = @pending_order.status
    @pending_order.status = params[:order][:status].downcase

    respond_to do |format|
      if @pending_order.save
        if old_status != 'delivered' && @pending_order.status == 'delivered'
          @pending_order.order_items.each do |item|
            item.product.decrement!(:quantity, item.quantity)
          end
        end
        format.html { redirect_to admin_dashboard_path, notice: "Pending order status updated successfully!" }
      else
        format.html { render admin_dashboard_path, status: :unprocessable_entity }
      end
    end
  end

  def all_products
    @q = Product.ransack(params[:q])
    @products = @q.result.page(params[:page]).per(10)
  end

  def download_order
    order = Order.find(params[:id])

    pdf = Prawn::Document.new do
      # User and Order Details
      text "Order Details", size: 20, style: :bold
      move_down 10
      text "Customer Name: #{order.user.full_name}"
      text "Delivery Address: #{order.delivery_address}"
      text "Order Number: #{order.order_number}"
      text "Order Date: #{order.created_at.strftime('%B %d, %Y %I:%M %p')}"
      if order.payment_method == "cash_on_delivery"
        text "Payment Method: Cash On Delivery"
      elsif order.payment_method == "online_payment"
        text "Payment Method: Online Payment Via Stripe"
        text "Stripe Charge ID: #{order.stripe_charge_id}"
      end

      if order.delivery_method == "home_delivery"
        text "Delivery Method: Home Delivery"
      elsif order.delivery_method == "store_pickup"
        text "Delivery Method: Store Pickup"
      end
      move_down 20

      # Table for Order Items
      items_data = [["Serial", "Product Name", "Price", "Quantity", "Total Price"]]
      order.order_items.each_with_index do |item, index|
        items_data << [
          index + 1,
          item.product.name,
          "$#{item.price}",
          item.quantity,
          "$#{item.price * item.quantity}"
        ]
      end
      table(items_data, header: true, position: :center, column_widths: [50, 150, 100, 100, 100], cell_style: { align: :center })

      # Total Price
      sub_total_price = order.order_items.sum { |item| item.price * item.quantity }
      if order.delivery_method == "home_delivery"
        move_down 10
        text "Sub Total: $#{sub_total_price}", style: :bold, align: :right
        text "Delivery Charge: $10", style: :bold, align: :right
        if order.payment_method == "online_payment" && order.is_payment_completed
          text "Amount Paid: $#{order.total_price}", style: :bold, align: :right
        else
          text "Cash To Pay: $#{order.total_price}", style: :bold, align: :right
        end
      elsif order.delivery_method == "store_pickup"
        move_down 10
        text "Sub Total: $#{sub_total_price}", style: :bold, align: :right
        text "Delivery Charge: $0", style: :bold, align: :right
        if order.payment_method == "online_payment" && order.is_payment_completed
          text "Amount Paid: $#{order.total_price}", style: :bold, align: :right
        else
          text "Cash To Pay: $#{order.total_price}", style: :bold, align: :right
        end
      end
      move_down 20
      text "Thank you for ordering from Galaxy Tech. If you have any complaints about this order, please call us at 123-456-789 or email us at support@galaxytech.com."
      text "This is a system generated invoice and no signature or seal is required."
    end


    pdf.number_pages "Page <page> of <total>", { start_count_at: 1, at: [pdf.bounds.right - 100, 0], align: :right, size: 8 }
    send_data pdf.render, filename: "order_#{order.order_number}.pdf", type: 'application/pdf', disposition: 'attachment'
  end

  private

  def authenticate_admin
    unless current_user&.admin?
      redirect_to root_path, alert: 'Access denied!'
    end
  end


end

app/helpers/admin_dashboards_helper.rb
module AdminDashboardsHelper
end

app/views/admin_dashboards/_product.html.erb
<div>
  Name: <%= link_to product.name, product_path(product) %>
</div>

app/views/admin_dashboards/all_products.html.erb
<h1 class="text-2xl font-bold mb-4 text-center">All the products</h1>
<table class="w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
  <tr class="bg-gray-100 border-b">
    <th class="px-4 py-2 border-r border-gray-200">Image</th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :name %></th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :price %></th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :quantity %></th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :brand %></th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :component %></th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :created_at %></th>
    <th class="px-4 py-2 border-r border-gray-200"><%= sort_link @q, :updated_at %></th>
    <th class="px-4 py-2 border-r border-gray-200">Actions</th>
  </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
  <% @products.each do |product| %>
    <tr class="border-b">
      <td class="px-4 py-2 border-r border-gray-200 flex justify-center items-center"><%= image_tag product.product_image, class: "h-16" %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.name %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.price %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.quantity %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.brand %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.component %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.created_at.strftime("%d %b %Y %I:%M:%S %p") %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= product.updated_at.strftime("%d %b %Y %I:%M:%S %p") %></td>
      <td class="px-4 py-2 px-4 py-2 flex space-x-2">
        <%= link_to 'View', product_path(product), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <%= link_to 'Edit', edit_product_path(product), class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
        <%= link_to "Delete", product_path(product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="pagination-container">
<%= paginate @products %>
</div>

app/views/admin_dashboards/index.html.erb
<div class="bg-gray-100 min-h-screen py-8">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold text-gray-800 mb-6 text-center">Admin Dashboard</h1>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-lg font-semibold mb-2 text-center">User Statistics</h2>
        <p class="text-gray-600 mb-2">Total Users: <%= @total_users %></p>
        <p class="text-gray-600 mb-2">Confirmed Users: <%= @confirmed_users %></p>
        <p class="text-gray-600 mb-2">Unconfirmed Users: <%= @unconfirmed_users %></p>
        <p class="text-gray-600">Admin Users: <%= @admin_users %></p>
      </div>

      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-lg font-semibold mb-4 text-center">Total Sales Over Time</h2>
        <%= line_chart @total_sales_over_time, library: {animation: {duration: 1000}}, class: "h-64" %>
      </div>

      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-lg font-semibold mb-4 text-center">Top Selling Products</h2>
        <%= column_chart @top_selling_products, library: {animation: {duration: 1000}}, class: "h-64" %>
      </div>

      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-lg font-semibold mb-4 text-center">Sales by Payment Method</h2>
        <%= pie_chart @sales_by_payment_method, library: {animation: {duration: 1000}}, class: "h-64" %>
      </div>

      <div class="bg-white shadow-md rounded-lg p-6">
        <h2 class="text-lg font-semibold mb-4 text-center">Products by Component</h2>
        <%= pie_chart @products_by_component, donut: true, library: {animation: {duration: 1000}}, class: "h-64" %>
      </div>
    </div>
  </div>
</div>

app/views/admin_dashboards/pending_orders.html.erb
<h1 class="text-2xl font-bold mb-4 text-center">
  Pending orders
</h1>

<table class="w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
  <tr class="bg-gray-100 border-b">
    <th class="px-4 py-2 border-r border-gray-200">Customer Name</th>
    <th class="px-4 py-2 border-r border-gray-200">Order Number</th>
    <th class="px-4 py-2 border-r border-gray-200">Total Price</th>
    <th class="px-4 py-2 border-r border-gray-200">Order Status</th>
    <th class="px-4 py-2 border-r border-gray-200">Action</th>
  </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
  <% @pending_orders.each do |pending_order| %>
    <tr class="border-b">
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= pending_order.user.full_name %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= pending_order.order_number %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= pending_order.total_price %></td>
      <td class="px-4 py-2 border-r border-gray-200 text-center"><%= pending_order.status %></td>
      <td class="px-4 py-2 px-4 py-2 flex space-x-2"><%= link_to "View Order", admin_dashboard_path(pending_order), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div class="pagination-container">
  <%= paginate @pending_orders %>
</div>

app/views/admin_dashboards/show.html.erb
<div class="max-w-3xl mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
  <div class="px-6 py-4">
    <div class="flex items-center mb-4">
      <span class="font-bold text-gray-700 mr-2">Customer Name:</span>
      <span class="text-gray-800"><%= @pending_order.user.full_name %></span>
    </div>
    <div class="flex items-center mb-4">
      <span class="font-bold text-gray-700 mr-2">Order Number:</span>
      <span class="text-gray-800"><%= @pending_order.order_number %></span>
    </div>
    <div class="flex items-center mb-4">
      <span class="font-bold text-gray-700 mr-2">Total Price:</span>
      <span class="text-gray-800"><%= @pending_order.total_price %></span>
    </div>
  </div>

  <div class="bg-gray-100 px-6 py-4">
    <h3 class="font-bold text-gray-700 mb-2">Order Items:</h3>
    <% @pending_order.order_items.each do |pending_order_item| %>
      <div class="flex items-center mb-2">
        <span class="font-bold text-gray-700 mr-2">Product Name:</span>
        <span class="text-gray-800"><%= pending_order_item.product.name %></span>
      </div>
      <div class="flex items-center mb-4">
        <span class="font-bold text-gray-700 mr-2">Quantity:</span>
        <span class="text-gray-800"><%= pending_order_item.quantity %></span>
      </div>
    <% end %>
    <div>
      <%= link_to "Download Order", download_order_admin_dashboard_path, class: 'px-4 py-2 rounded-md bg-indigo-600 text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500', data: {turbo: false} %>
    </div>
  </div>


  <div class="px-6 py-4 bg-white">
    <h3 class="font-bold text-gray-700 mb-4">Update Order Status</h3>
    <%= form_with(model: @pending_order, url: change_customer_order_status_admin_dashboard_path) do |form| %>
      <div class="mb-4">
        <%= form.select :status, ['Processing', 'Shipped', 'Delivered'], { selected: @pending_order.status.capitalize }, class: "shadow appearance-none border rounded w-1/5 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <%= form.submit 'Update Order Status', class: 'px-4 py-2 rounded-md bg-indigo-600 text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500' %>
    <% end %>

  </div>
</div>