config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations',
                                      omniauth_callbacks: 'callbacks',
                                      passwords: 'passwords',}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :search_product
      get :search_product_by_component
    end
    member do
      post :add_to_cart
      post :increase_quantity
      post :decrease_quantity
    end
    resources :cart_items do
      member do
        post :increase_quantity
        post :decrease_quantity
      end
    end
  end

  resources :carts do
    member do
      post :increase_quantity
      post :decrease_quantity
    end
  end

  resources :orders do
    resources :product_ratings_and_reviews
    collection do
      get :checkout
      post :submit_stripe_payment
    end

    member do
      get :stripe_payment
    end
  end


  resources :admin_dashboards do
    collection do
      get :pending_orders
      get :all_products
    end
    member do
      patch :change_customer_order_status
      get :download_order
    end
  end

  resources :add_to_wish_lists

end

app/models/product.rb
class Product < ApplicationRecord

  def self.ransackable_attributes(auth_object = nil)
    ["name", "price", "component", "brand", "quantity", "created_at", "updated_at"]
  end

  validates :product_image, presence: true
  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :brand, presence: true
  validates :component, presence: true

  validate :product_image_size_under_limit
  validate :product_image_must_be_image

  has_rich_text :key_features
  has_rich_text :specification
  has_rich_text :description
  has_one_attached :product_image

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :product_rating_and_reviews, dependent: :destroy
  has_many :add_to_wish_lists, dependent: :destroy
  has_many :users, through: :add_to_wish_lists

  before_destroy :purge_product_image
  before_update :purge_product_image, if: :product_image_changed?

  private
  def product_image_size_under_limit
    if product_image.attached? && product_image.blob.byte_size > 5.megabytes
      product_image.purge
      errors.add(:product_image, 'is too large (max is 5MB)')
    end
  end

  def product_image_must_be_image
    if product_image.attached? && !product_image.content_type.start_with?('image/')
      product_image.purge
      errors.add(:product_image, 'must be an image file')
    end
  end

  def purge_product_image
    if Rails.env.production?
      public_id = "ruby_on_rails/galaxy_tech/#{product_image.key}"
      Cloudinary::Api.delete_resources([public_id], type: :upload, resource_type: :image)
    end
  end

  def product_image_changed?
    product_image.attached? && product_image.attachment.blob_id_changed?
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_admin, only: [:new, :edit, :create, :update, :destroy]
  before_action :test_admin_cannot_delete_product, only: [:destroy]

  def index
    @products = Product.page(params[:page]).per(18)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html {redirect_to admin_dashboards_path, notice: "Product created successfully"}
      else
        format.html {render 'new', status: :unprocessable_entity}
      end
    end
  end

  def show
    @product = Product.find(params[:id])
    @cart = current_user.cart if user_signed_in?
    @title = @product.name
    average_rating = ProductRatingAndReview.where(product_id: @product.id).average(:rating)
    @average_rating = average_rating ? average_rating.round(2) : nil
    @rating_count = ProductRatingAndReview.where(product_id: @product.id).count
    @product_reviews = ProductRatingAndReview.where(product_id: @product)
    @wishlist_item = current_user.add_to_wish_lists.find_by(product: @product) if user_signed_in?
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html {redirect_to admin_dashboards_path, notice: "Product updated successfully!"}
      else
        format.html {render 'edit', status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_dashboards_path, notice: "Product deleted successfully!"
  end

  def search_product
    @q = Product.ransack(name_cont: params[:product_name], component_cont: params[:product_name], brand_cont: params[:product_name], m: 'or')
    @products = @q.result(distinct: true).page(params[:page]).per(10)
  end


  def search_product_by_component
    start_price = params[:start_price] ? params[:start_price].gsub(',', '').to_d : 0
    end_price = params[:end_price] ? params[:end_price].gsub(',', '').to_d : Float::INFINITY

    query = { component_eq: params[:component] }
    if start_price != 0 || end_price != 0
      query[:price_gteq] = start_price
      query[:price_lteq] = end_price
    end
    query[:brand_in] = params[:brands] if params[:brands].present?
    query[:quantity_gt] = 0 if params[:in_stock] == 'In stock'

    @q = Product.ransack(query)
    @products = @q.result.page(params[:page]).per(5)
    @highest_price = Product.where(component: params[:component]).maximum(:price)
    @brands = Product.where(component: params[:component]).pluck(:brand).uniq
  end

  def add_to_cart
    if current_user.nil?
      redirect_to new_user_session_path, alert: 'You must be logged in to add items to the cart.'
      return
    end
    @product = Product.find(params[:id])
    @cart = current_user.cart || current_user.create_cart

    @cart_item = @cart.cart_items.find_by(product: @product)

    if @cart_item
      @cart_item.increment!(:quantity)
    else
      @cart_item = @cart.cart_items.new(product: @product, quantity: 1)
    end

    if @cart_item.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("search_product_by_component_add_inc_dec_#{@product.id}", partial: "search_product_by_component_add_inc_dec", locals: { product: @product }) +
            turbo_stream.update("cart_info", partial: "cart_items/cart_info", locals: { cart: @cart })
        end
        format.html { redirect_to search_product_by_component_products_path }
      end
    else
      redirect_to product_path(@product), alert: 'There was an error adding the product to the cart.'
    end
  end

  def increase_quantity
    @product = Product.find(params[:id])
    @cart_item = CartItem.find_by(cart: current_user.cart, product_id: params[:id])

    if @cart_item
      @cart_item.increment!(:quantity)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("search_product_by_component_add_inc_dec_#{@product.id}", partial: "search_product_by_component_add_inc_dec", locals: { product: @product }) +
            turbo_stream.update("cart_info", partial: "cart_items/cart_info", locals: { cart: @cart })
        end
      end
    else
      redirect_to product_path(params[:product_id]), alert: 'There was an error increasing the quantity.'
    end
  end

  def decrease_quantity
    @product = Product.find(params[:id])
    @cart_item = CartItem.find_by(cart: current_user.cart, product_id: params[:id])

    if @cart_item
      if @cart_item.quantity > 1
        @cart_item.decrement!(:quantity)
      else
        @cart = @cart_item.cart
        @cart_item.destroy
        @cart.destroy if @cart.cart_items.empty?
      end
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("search_product_by_component_add_inc_dec_#{@product.id}", partial: "search_product_by_component_add_inc_dec", locals: { product: @product }) +
            turbo_stream.update("cart_info", partial: "cart_items/cart_info", locals: { cart: @cart })
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("search_product_by_component_add_inc_dec_#{@product.id}", partial: "search_product_by_component_add_inc_dec", locals: { product: @product }) +
            turbo_stream.update("cart_info", partial: "cart_items/cart_info", locals: { cart: @cart })
        end
        format.html { redirect_to product_path(params[:id]), alert: 'There was an error decreasing the quantity.' }
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quantity, :brand, :key_features,
                                    :specification, :description, :product_image, :component)
  end

  def authenticate_admin
    unless current_user&.admin?
      redirect_to root_path, alert: 'Access denied!'
    end
  end

  def test_admin_cannot_delete_product
    if current_user&.admin? && current_user.email == 'testadmin@gmail.com'
      redirect_to root_path, alert: 'Test admin does not have permission to delete this product.!'
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart_increase_decrease_quantity.html.erb
<turbo-frame id="add_to_cart_increase_decrease_quantity">
  <% if current_user && current_user.cart&.products&.include?(product) %>
    <% cart_item = current_user.cart.cart_items.find_by(product: product) %>
    <div class="flex items-center">
      <%= button_to "-", decrease_quantity_product_cart_item_path(product, current_user.cart.cart_items.find_by(product: product)), method: :post, class: "w-8 px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300 mr-1" %>
      <p class="text-gray-700 mx-1"><%= cart_item.quantity %> in cart</p>
      <% if cart_item.quantity >= product.quantity %>
        <button class="w-8 px-3 py-2 bg-gray-300 text-gray-700 rounded-md ml-1" disabled>+</button>
      <% else %>
        <%= button_to "+", increase_quantity_product_cart_item_path(product, cart_item), method: :post, class: "w-8 px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300 ml-1" %>
      <% end %>
    </div>
  <% else %>
    <% if product.quantity.zero? %>
      <button class="px-3 py-2 bg-gray-300 text-gray-700 rounded-md" disabled>OUT OF STOCK</button>
    <% elsif user_signed_in? && !current_user.admin? %>
      <%= button_to "Add to cart", product_cart_items_path(product), method: :post, class: "px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300" %>
    <% end %>
  <% end %>
</turbo-frame>

app/views/products/_add_to_wishlist_button.html.erb
<div>
  <turbo-frame id="add_to_wishlist_button">
    <% if user_signed_in? && !current_user.admin? %>
      <% if wishlist_item %>
        <%= button_to "Remove from wishlist", add_to_wish_list_path(wishlist_item), method: :delete, class: "px-4 py-2 text-sm font-medium text-red-600 bg-white border border-red-300 rounded-md hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors duration-300" %>
      <% else %>
        <%= button_to "Add to wishlist", add_to_wish_lists_path(product_id: product.id), method: :post, class: "px-4 py-2 text-sm font-medium text-indigo-600 bg-white border border-indigo-300 rounded-md hover:bg-indigo-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-300" %>
      <% end %>
    <% end %>
  </turbo-frame>
</div>

app/views/products/_search_product_by_component_add_inc_dec.html.erb
<turbo-frame id="search_product_by_component_add_inc_dec_<%= product.id %>">
  <% if current_user && current_user.cart&.products&.include?(product) %>
    <% cart_item = current_user.cart.cart_items.find_by(product: product) %>
    <div class="flex items-center justify-between">
      <%= button_to "-", decrease_quantity_product_path(product, current_user.cart.cart_items.find_by(id: product.id)), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 hover:bg-indigo-600" %>
      <p class="text-gray-700 mx-2"><%= cart_item.quantity %> in cart</p>
      <% if cart_item.quantity >= product.quantity %>
        <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2" disabled>+</button>
      <% else %>
        <%= button_to "+", increase_quantity_product_path(id: product.id, cart_item_id: cart_item.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 hover:bg-indigo-600" %>
      <% end %>
    </div>
  <% else %>
    <% if product.quantity.zero? %>
      <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2 w-full" disabled>OUT OF STOCK</button>
    <% elsif user_signed_in? && !current_user.admin? %>
      <%= button_to "Add to cart", add_to_cart_product_path(id: product.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 w-full hover:bg-indigo-600" %>
    <% end %>
  <% end %>
</turbo-frame>

app/views/products/edit.html.erb
<div class="container mx-auto px-4">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <h2 class="text-2xl font-semibold text-gray-800 mb-6">Edit Product</h2>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/index.html.erb
<% if params[:page].blank? || params[:page].to_i == 1 %>
  <h1 class="text-3xl font-bold text-center mb-8">Welcome to Galaxy Tech</h1>
<% end %>

<div class="container mx-auto">
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
    <% @products.each do |product| %>
      <div class="bg-white rounded-lg shadow-md flex flex-col">
        <% cache product do %>
          <% if product.product_image.attached? %>
            <div class="aspect-w-16 aspect-h-9">
              <%= link_to image_tag(product.product_image, class: "object-cover w-full h-full"), product_path(product) %>
            </div>
          <% end %>
          <div class="p-4 flex flex-col justify-between flex-1">
            <div class="flex flex-col justify-between">
              <div>
                <h2 class="text-xl font-semibold mb-2">
                  <%= link_to product.name, product_path(product), class: "text-indigo-600 hover:text-indigo-700" %>
                </h2>
              </div>
              <div>
                <p class="text-gray-700">
                  <%= number_with_delimiter(number_with_precision(product.price, precision: 2), delimiter: ',') %> USD
                </p>
              </div>
            </div>
            <div>
        <% end %>
            <% if user_signed_in? %>
              <turbo-frame id="search_product_by_component_add_inc_dec_<%= product.id %>">
                <% if current_user && current_user.cart&.products&.include?(product) %>
                  <% cart_item = current_user.cart.cart_items.find_by(product: product) %>
                  <div class="flex items-center justify-between">
                    <%= button_to "-", decrease_quantity_product_path(product, current_user.cart.cart_items.find_by(id: product.id)), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 hover:bg-indigo-600" %>
                    <p class="text-gray-700 mx-2"><%= cart_item.quantity %> in cart</p>
                    <% if cart_item.quantity >= product.quantity %>
                      <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2" disabled>+</button>
                    <% else %>
                      <%= button_to "+", increase_quantity_product_path(id: product.id, cart_item_id: cart_item.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 hover:bg-indigo-600" %>
                    <% end %>
                  </div>
                <% else %>
                  <% if product.quantity.zero? %>
                    <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2 w-full" disabled>OUT OF STOCK</button>
                  <% elsif user_signed_in? && !current_user.admin? %>
                    <%= button_to "Add to cart", add_to_cart_product_path(id: product.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 w-full hover:bg-indigo-600" %>
                  <% end %>
                <% end %>
              </turbo-frame>
            <%else %>
              <% if product.quantity.zero? %>
                <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2 w-full" disabled>OUT OF STOCK</button>
              <% elsif !current_user&.admin? %>
                <%= button_to "Add to cart", add_to_cart_product_path(id: product.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 w-full hover:bg-indigo-600" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="pagination-container">
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div class="container mx-auto px-4">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <h2 class="text-2xl font-semibold text-gray-800 mb-6">Add New Product</h2>
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/products/search_product.html.erb
<div class="container mx-auto">
  <% if @products.any? %>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
      <% @products.each do |product| %>
        <div class="bg-white rounded-lg shadow-md overflow-hidden">
          <% if product.product_image.attached? %>
            <div class="aspect-w-16 aspect-h-9">
              <%= link_to image_tag(product.product_image, class: "object-cover w-full h-full"), product_path(product) %>
            </div>
          <% end %>
          <div class="p-4">
            <h2 class="text-xl font-semibold mb-2">
              <%= link_to product.name, product_path(product), class: "text-indigo-600 hover:text-indigo-700" %>
            </h2>
            <p class="text-gray-700 mb-4">
              <%= number_with_delimiter(number_with_precision(product.price, precision: 2), delimiter: ',') %> USD
            </p>
            <div>
              <% if user_signed_in? %>
                <turbo-frame id="search_product_by_component_add_inc_dec_<%= product.id %>">
                  <% if current_user && current_user.cart&.products&.include?(product) %>
                    <% cart_item = current_user.cart.cart_items.find_by(product: product) %>
                    <div class="flex items-center justify-between">
                      <%= button_to "-", decrease_quantity_product_path(product, current_user.cart.cart_items.find_by(id: product.id)), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 hover:bg-indigo-600" %>
                      <p class="text-gray-700 mx-2"><%= cart_item.quantity %> in cart</p>
                      <% if cart_item.quantity >= product.quantity %>
                        <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2" disabled>+</button>
                      <% else %>
                        <%= button_to "+", increase_quantity_product_path(id: product.id, cart_item_id: cart_item.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 hover:bg-indigo-600" %>
                      <% end %>
                    </div>
                  <% else %>
                    <% if product.quantity.zero? %>
                      <button class="bg-gray-300 text-gray-700 rounded py-2 px-4 mb-2 w-full" disabled>OUT OF STOCK</button>
                    <% elsif user_signed_in? && !current_user.admin? %>
                      <%= button_to "Add to cart", add_to_cart_product_path(id: product.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 mb-2 w-full hover:bg-indigo-600" %>
                    <% end %>
                  <% end %>
                </turbo-frame>
              <% else %>
                <% if product.quantity.zero? %>
                  <button class="bg-gray-300 text-gray-700 rounded py-2 px-4" disabled>OUT OF STOCK</button>
                <% elsif !current_user&.admin? %>
                  <%= button_to "Add to cart", add_to_cart_product_path(id: product.id), method: :post, class: "bg-indigo-500 text-white rounded py-2 px-4 hover:bg-indigo-600" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="bg-white rounded-lg shadow-md p-6">
      <p class="text-gray-700">There are no products that match the search criteria.</p>
    </div>
  <% end %>
</div>
<div class="pagination-container">
  <%= paginate @products %>
</div>

app/views/products/show.html.erb
<div class="max-w-4xl mx-auto py-8">
  <div class="flex flex-col md:flex-row">
    <div class="md:w-1/2 mb-6 md:mb-0">
      <% if @product.product_image.attached? %>
        <%= image_tag @product.product_image, class: "w-full rounded-lg shadow-md" %>
      <% end %>
    </div>
    <div class="md:w-1/2 md:pl-8">
      <div class="flex justify-between items-center mb-4">
        <h1 class="text-3xl font-bold text-gray-800"><%= @product.name %></h1>
        <% if user_signed_in? && current_user.admin? %>
          <div class="flex space-x-2">
            <%= link_to "Edit", edit_product_path(@product), class: "px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300" %>
            <%= link_to "Delete", product_path(@product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "px-3 py-2 bg-red-500 text-white rounded-md hover:bg-red-600 transition-colors duration-300" %>
          </div>
        <% end %>
      </div>
      <p class="text-2xl font-semibold text-gray-700 mb-4">
        <%= number_with_delimiter(number_with_precision(@product.price, precision: 2), delimiter: ',') %> USD
      </p>
      <div>
        <turbo-frame id="add_to_wishlist_button">
          <% if user_signed_in? && !current_user.admin? %>
            <% if @wishlist_item %>
              <%= button_to "Remove from wishlist", add_to_wish_list_path(@wishlist_item), method: :delete, class: "px-4 py-2 text-sm font-medium text-red-600 bg-white border border-red-300 rounded-md hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors duration-300" %>
            <% else %>
              <%= button_to "Add to wishlist", add_to_wish_lists_path(product_id: @product.id), method: :post, class: "px-4 py-2 text-sm font-medium text-indigo-600 bg-white border border-indigo-300 rounded-md hover:bg-indigo-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 transition-colors duration-300" %>
            <% end %>
          <% end %>
        </turbo-frame>
      </div>
      <div class="mb-4">
        <% if user_signed_in? && current_user.admin? %>
          <p class="text-gray-600">Quantity: <%= @product.quantity %></p>
        <% else %>
          <p class="text-gray-600">
            Status: <span class="<%= @product.quantity > 0 ? 'text-green-500' : 'text-red-500' %>"><%= @product.quantity > 0 ? 'In stock' : 'Out of stock' %></span>
          </p>
        <% end %>
      </div>
      <p class="text-gray-600 mb-4">Brand: <%= @product.brand %></p>
      <p class="text-gray-600 mb-4">
        Rating:
        <% if @average_rating.nil? %>
          Nobody rated yet.
          <a href="#reviews" class="text-emerald-600 font-semibold hover:text-emerald-800 hover:underline transition duration-300 ease-in-out scroll-smooth relative inline-block">
            See reviews
            <span class="absolute bottom-0 left-0 w-full h-0.5 bg-emerald-600 transform origin-bottom scale-x-0 transition-transform duration-300 ease-out group-hover:scale-x-100"></span>
          </a>
        <% else %>
          <%= @average_rating %> (based on <%= @rating_count %> ratings)
          <a href="#reviews" class="text-emerald-600 font-semibold hover:text-emerald-800 hover:underline transition duration-300 ease-in-out scroll-smooth relative inline-block">
            See reviews
            <span class="absolute bottom-0 left-0 w-full h-0.5 bg-emerald-600 transform origin-bottom scale-x-0 transition-transform duration-300 ease-out group-hover:scale-x-100"></span>
          </a>
        <% end %>
      </p>
      <div class="mb-4">
        <% if user_signed_in? %>
          <turbo-frame id="add_to_cart_increase_decrease_quantity">
            <% if current_user && current_user.cart&.products&.include?(@product) %>
              <% cart_item = current_user.cart.cart_items.find_by(product: @product) %>
              <div class="flex items-center">
                <%= button_to "-", decrease_quantity_product_cart_item_path(@product, current_user.cart.cart_items.find_by(product: @product)), method: :post, class: "w-8 px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300 mr-1" %>
                <p class="text-gray-700 mx-1"><%= cart_item.quantity %> in cart</p>
                <% if cart_item.quantity >= @product.quantity %>
                  <button class="w-8 px-3 py-2 bg-gray-300 text-gray-700 rounded-md ml-1" disabled>+</button>
                <% else %>
                  <%= button_to "+", increase_quantity_product_cart_item_path(@product, cart_item), method: :post, class: "w-8 px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300 ml-1" %>
                <% end %>
              </div>
            <% else %>
              <% if @product.quantity.zero? %>
                <button class="px-3 py-2 bg-gray-300 text-gray-700 rounded-md" disabled>OUT OF STOCK</button>
              <% elsif user_signed_in? && !current_user.admin? %>
                <%= button_to "Add to cart", product_cart_items_path(@product), method: :post, class: "px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300" %>
              <% end %>
            <% end %>
          </turbo-frame>
        <% else %>
          <% if @product.quantity.zero? %>
            <button class="px-3 py-2 bg-gray-300 text-gray-700 rounded-md" disabled>OUT OF STOCK</button>
          <% elsif !current_user&.admin? %>
            <%= button_to "Add to cart", product_cart_items_path(@product), method: :post, class: "px-3 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors duration-300" %>
          <% end %>
        <% end %>
      </div>
      <% cache @product do %>
        <div class="mb-4">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">Key Features</h2>
          <p class="text-gray-600"><%= @product.key_features %></p>
        </div>
        <div class="mb-4">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">Specification</h2>
          <p class="text-gray-600"><%= @product.specification %></p>
        </div>
        <div class="mb-4">
          <h2 class="text-xl font-semibold text-gray-800 mb-2">Description</h2>
          <p class="text-gray-600"><%= @product.description %></p>
        </div>
      <% end %>
    </div>
  </div>
  <div id="reviews" class="bg-white shadow rounded-lg p-6">
    <h3 class="text-2xl font-semibold text-gray-800 mb-4">Reviews</h3>
    <% if @product_reviews.empty? %>
      <div class="text-gray-600 italic">
        Review not available.
      </div>
    <% else %>
      <div class="space-y-6">
        <% @product_reviews.each do |product_review| %>
          <div class="bg-gray-100 p-4 rounded-md">
            <div class="font-medium text-gray-700 mb-2">
              <%= product_review.user.full_name %>:
            </div>
            <div class="text-gray-600">
              <%= product_review.review %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>