config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations',
                                      omniauth_callbacks: 'callbacks',
                                      passwords: 'passwords',}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :search_product
      get :search_product_by_component
    end
    member do
      post :add_to_cart
      post :increase_quantity
      post :decrease_quantity
    end
    resources :cart_items do
      member do
        post :increase_quantity
        post :decrease_quantity
      end
    end
  end

  resources :carts do
    member do
      post :increase_quantity
      post :decrease_quantity
    end
  end

  resources :orders do
    resources :product_ratings_and_reviews
    collection do
      get :checkout
      post :submit_stripe_payment
    end

    member do
      get :stripe_payment
    end
  end


  resources :admin_dashboards do
    collection do
      get :pending_orders
      get :all_products
    end
    member do
      patch :change_customer_order_status
      get :download_order
    end
  end

  resources :add_to_wish_lists

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title ? "#{@title} | Galaxy Tech" : "Galaxy Tech" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="turbo-cache-control" content="no-cache">
    <meta name="view-transition" content="same-origin" />
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body class="flex flex-col min-h-screen bg-gray-100">
  <div class="container mx-auto px-4 py-8">
    <div class="flex flex-wrap items-center justify-between mb-8">
      <%= link_to root_path do %>
        <%= image_tag 'Galaxytechv2.svg', alt: 'Galaxy Tech', class: 'h-12' %>
      <% end %>
      <div class="flex items-center ml-auto">
        <%= form_with url: search_product_products_path, method: :get, class: 'flex mx-auto' do |form| %>
          <%= form.text_field :product_name, placeholder: "Search", required: true, value: (params[:product_name] unless current_page?(root_path)), autocomplete: 'off', class: 'border border-gray-300 rounded-l-md px-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500' %>
          <%= form.button type: :submit, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-r-md hidden" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
      <div class="flex items-center ml-8">
        <div class="relative">
          <% if user_signed_in? %>
            <div class="relative group" data-controller="dropdown">
              <div class="flex items-center cursor-pointer py-2 px-3 rounded-md transition duration-300 hover:bg-indigo-500 hover:text-white" data-dropdown-target="trigger" data-action="mouseenter->dropdown#showMenu mouseleave->dropdown#hideMenu">
                <div class="w-8 h-8 mr-2 transition duration-300 group-hover:invert">
                  <%= image_tag "customer_icon.png" %>
                </div>
                <div class="text-sm transition duration-300 group-hover:text-black">
                  <div>Hello, <%= current_user.full_name %></div>
                  <% if user_signed_in? && !current_user.admin? %>
                    <div>Orders &amp; account</div>
                  <% end %>
                </div>
              </div>
              <div class="absolute left-0 mt-1 -ml-2 hidden bg-white border rounded-md shadow-lg z-10 transition duration-300 transform origin-top scale-0 group-hover:scale-100" data-dropdown-target="menu" data-action="mouseenter->dropdown#showMenu mouseleave->dropdown#hideMenu">
                <% if current_user.admin? %>
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to "Admin Dashboard", admin_dashboards_path, class: 'block px-4 py-2' %>
                  </div>
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to "Add Product", new_product_path, class: 'block px-4 py-2' %>
                  </div>
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to "All product", all_products_admin_dashboards_path, class: 'block px-4 py-2' %>
                  </div>
<!--                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">-->
                    <%#= link_to "Discount Product", admin_dashboards_path, class: 'block px-4 py-2' %>
<!--                  </div>-->
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to "Pending Orders", pending_orders_admin_dashboards_path, class: 'block px-4 py-2' %>
                  </div>
<!--                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">-->
                    <%#= link_to "Payments", admin_dashboards_path, class: 'block px-4 py-2' %>
<!--                  </div>-->
                <% else %>
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to 'My Orders', orders_path, class: 'block px-4 py-2' %>
                  </div>
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to 'My Wishlists', add_to_wish_lists_path, class: 'block px-4 py-2' %>
                  </div>
                  <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                    <%= link_to 'Edit profile', edit_user_registration_path, class: 'block px-4 py-2' %>
                  </div>
                <% end %>
                <div class="px-4 text-gray-700 transition duration-300 hover:bg-indigo-500 hover:text-white">
                  <%= button_to "Log Out", destroy_user_session_url, method: "delete", class: 'w-full text-left block px-4 py-2' %>
                </div>
              </div>
            </div>
          <% else %>
            <div class="flex items-center space-x-4">
              <div>
                <%= button_to "Log In", new_user_session_url, method: "get", class: 'bg-blue-500 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-300' %>
              </div>
              <div>
                <%= button_to "Sign Up", new_user_registration_url, method: "get", class: 'bg-green-500 hover:bg-green-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-300' %>
              </div>
            </div>
          <% end %>
        </div>
        <turbo-frame id="cart_info" class="flex items-center ml-4">
          <div class="mr-4">
            <% if user_signed_in? && !current_user.admin? %>
              <div class="flex items-center">
                <% if @cart %>
                  <div class="mr-2">
                    <%= link_to carts_path, data: {turbo_frame: "_top"} do %>
                      <%= image_tag "cart_icon.png", alt: "cart icon", width: "24", height: "24" %>
                    <% end %>
                  </div>
                  (<%= @cart.cart_items.sum(:quantity) || 0 %>)
                <% else %>
                  <div class="mr-2">
                    <%= link_to carts_path, data: {turbo_frame: "_top"} do %>
                      <%= image_tag "cart_icon.png", alt: "cart icon", width: "24", height: "24" %>
                    <% end %>
                  </div>
                  (<%= @cart&.cart_items&.sum(:quantity) || 0 %>)
                <% end %>
              </div>
              <div class="text-indigo-600 font-semibold max-w-xs overflow-hidden whitespace-nowrap overflow-ellipsis">
                <%= number_to_currency(@cart&.total_price || 0, unit: '', format: "%n %u") %> USD
              </div>
            <% end %>
          </div>
        </turbo-frame>
      </div>
    </div>

    <div class="flex flex-wrap justify-center -mx-2 my-8">
      <% @components.each do |component| %>
        <% next if component.blank? %>
        <%= link_to component, search_product_by_component_products_path(component: component), class: 'component-link bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-md m-2' %>
      <% end %>
    </div>
  </div>

  <% if alert || notice %>
    <div class="mb-8 w-full max-w-md mx-auto">
      <% if notice %>
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded-md text-center animate-fade-in relative">
          <button type="button" class="absolute right-0 top-0 mt-2 mr-2 text-green-400 hover:text-green-500" onclick="this.parentElement.style.display='none';">&times;</button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-md text-center animate-fade-in relative">
          <button type="button" class="absolute right-0 top-0 mt-2 mr-2 text-red-400 hover:text-red-500" onclick="this.parentElement.style.display='none';">&times;</button>
          <%= alert %>
        </div>
      <% end %>
    </div>
  <% end %>

  <main class="flex-grow">
    <%= yield %>
  </main>
  <footer class="bg-gray-800 text-white py-8">
    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div>
          <h3 class="text-lg font-bold mb-4">About Us</h3>
          <p class="mb-4">We are a leading provider of high-quality PC components, dedicated to delivering top-notch products and excellent customer service.</p>
          <p class="mb-4">Explore our wide range of GPUs, CPUs, and other essential components to build your dream PC.</p>
        </div>
        <div>
          <h3 class="text-lg font-bold mb-4">Quick Links</h3>
          <ul class="space-y-2">
            <li><a href="/products/search_product_by_component?component=Graphics+Card" class="hover:text-gray-400 transition duration-300">GPUs</a></li>
            <li><a href="/products/search_product_by_component?component=Processor" class="hover:text-gray-400 transition duration-300">CPUs</a></li>
            <li><a href="/products/search_product_by_component?component=Motherboard" class="hover:text-gray-400 transition duration-300">Motherboards</a></li>
            <li><a href="/products/search_product_by_component?component=RAM+%28Desktop%29" class="hover:text-gray-400 transition duration-300">Memory</a></li>
            <li><a href="/products/search_product_by_component?component=Hard+Disk+Drive" class="hover:text-gray-400 transition duration-300">Storage</a></li>
          </ul>
        </div>
        <div>
          <h3 class="text-lg font-bold mb-4">Contact Us</h3>
          <p class="mb-4">Email: support@galaxytech.com</p>
          <p class="mb-4">Phone: 123-456-789</p>
          <div class="flex space-x-4">
            <a href="https://www.facebook.com/" target="_blank" class="text-gray-400 hover:text-white transition duration-300">
              <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/facebook/facebook-original.svg" />
              </svg>
            </a>
            <a href="https://x.com/home" target="_blank" class="text-gray-400 hover:text-white transition duration-300">
              <svg class="w-6 h-6 fill-current" viewBox="0 0 24 24">
                <img src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/twitter/twitter-original.svg" />
              </svg>
            </a>
          </div>
        </div>
      </div>
      <div class="mt-8 border-t border-gray-700 pt-4 text-center">
        &copy; <%= Date.today.year %> Galaxy Tech. All rights reserved.
      </div>
    </div>
  </footer>
  </body>
</html>